# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('image', models.ImageField(default='brands/None/no-img.jpg', upload_to='brands/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='state.State')),
            ],
        ),
    ]
