# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
