version: '3.6'

volumes: 
     pgdata:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    #networks:
    #  - suruse
  web:
    build: .
    command: python /code/manage.py migrate --noinput
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "5000:8000"
    depends_on:
      - db
  
