# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        ('vehicle_kind', '0001_initial'),
        ('brand', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city.City')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_kind.Kind')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='state.State')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('brand', 'city')]),
        ),
    ]
