# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_kind', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind',
            new_name='VehicleKind',
        ),
    ]
