# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='scanned_identification',
            field=models.FileField(default='scanned/default.jpg', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='brands/None/no-img.jpg', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='image',
            field=models.ImageField(default='kinds/None/no-img.jpg', upload_to='kinds/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enrollment',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.State'),
        ),
        migrations.AddField(
            model_name='brand',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.State'),
        ),
        migrations.AddField(
            model_name='kind',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.State'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.State'),
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.State'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.City'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.State'),
        ),
    ]
