# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
        migrations.RemoveField(
            model_name='uservehicle',
            name='state',
        ),
        migrations.RemoveField(
            model_name='uservehicle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservehicle',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='UserVehicle',
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Client'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.State'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Vehicle'),
        ),
    ]
