# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20181008_2127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('brand', 'city')]),
        ),
    ]
