# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20181008_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='state',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='clientvehicle',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientvehicle',
            name='state',
        ),
        migrations.RemoveField(
            model_name='clientvehicle',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='country',
            name='state',
        ),
        migrations.RemoveField(
            model_name='kind',
            name='state',
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='state',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientVehicle',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Kind',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
